// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlALq7Pmcbvs5M3cvrgB5jUxAatq2vfHY',
    appId: '1:798327108777:web:382538d7efb2963a1365b8',
    messagingSenderId: '798327108777',
    projectId: 'mobikul-ecommerce',
    authDomain: 'mobikul-ecommerce.firebaseapp.com',
    storageBucket: 'mobikul-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXZ-dBZ0nuCglsMe4uO8yuhz8e6U4UwuI',
    appId: '1:798327108777:android:1e9ba86b736bd5621365b8',
    messagingSenderId: '798327108777',
    projectId: 'mobikul-ecommerce',
    storageBucket: 'mobikul-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuTarKn97-QQqcZpF37Us2qAQaBCH4lCo',
    appId: '1:798327108777:ios:71cffad72a2647781365b8',
    messagingSenderId: '798327108777',
    projectId: 'mobikul-ecommerce',
    storageBucket: 'mobikul-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.ecommMobile',
  );
}
